M48
; DRILL file {KiCad 6.0.7-f9a2dced07~116~ubuntu22.04.1} date Tue 30 Aug 2022 10:25:03 PM PDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-30T22:25:03-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.7-f9a2dced07~116~ubuntu22.04.1
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
%
G90
G05
T1
X5.9055Y-3.9764
T2
X5.4055Y-4.4882
X5.9055Y-4.4882
T3
X4.7244Y-4.4882
X4.8244Y-4.4882
T0
M30
